import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    // My own build script cleans the dist directory, so I'll disable Vite's cleaning.
    // This ensures that the individual HTML pages generated by my script are preserved.
    emptyOutDir: false,
  },
});
